export { editionBlueprints, historicalPrograms, editionNocs, editionDelegations, sportCatalog, countries, namePools } from './historicalData.js'

export const rarityConfig = [
  { id: 'generational', label: 'Generational', min: 96, max: 100, chance: 0.0015 },
  { id: 'legend', label: 'Legend', min: 91, max: 95, chance: 0.009 },
  { id: 'epic', label: 'Epic', min: 85, max: 90, chance: 0.045 },
  { id: 'rare', label: 'Rare', min: 79, max: 84, chance: 0.17 },
  { id: 'uncommon', label: 'Uncommon', min: 70, max: 78, chance: 0.38 },
  { id: 'common', label: 'Common', min: 58, max: 69, chance: 1 },
]

export const careerProfiles = {
  'artistic-gymnastics': { debut: [15, 20], peak: [18, 23], span: [7, 13], decline: 2.6 },
  'rhythmic-gymnastics': { debut: [15, 19], peak: [18, 22], span: [6, 11], decline: 3.1 },
  trampolining: { debut: [17, 22], peak: [22, 27], span: [10, 16], decline: 1.8 },
  skateboarding: { debut: [13, 20], peak: [18, 25], span: [8, 16], decline: 2.0 },
  diving: { debut: [15, 20], peak: [20, 25], span: [10, 17], decline: 1.9 },
  swimming: { debut: [16, 21], peak: [21, 26], span: [9, 16], decline: 2.0 },
  'marathon-swimming': { debut: [18, 23], peak: [25, 30], span: [10, 18], decline: 1.4 },
  athletics: { debut: [18, 23], peak: [24, 29], span: [10, 18], decline: 1.5 },
  boxing: { debut: [18, 23], peak: [24, 29], span: [8, 14], decline: 1.8 },
  wrestling: { debut: [18, 23], peak: [25, 30], span: [10, 17], decline: 1.5 },
  judo: { debut: [18, 23], peak: [24, 29], span: [9, 16], decline: 1.7 },
  taekwondo: { debut: [17, 22], peak: [23, 28], span: [9, 15], decline: 1.8 },
  weightlifting: { debut: [18, 23], peak: [25, 30], span: [10, 17], decline: 1.5 },
  shooting: { debut: [19, 28], peak: [29, 38], span: [16, 28], decline: 0.7 },
  archery: { debut: [17, 25], peak: [25, 34], span: [13, 24], decline: 0.9 },
  sailing: { debut: [19, 27], peak: [28, 37], span: [15, 27], decline: 0.8 },
  'equestrian-dressage': { debut: [21, 31], peak: [34, 45], span: [18, 32], decline: 0.55 },
  'equestrian-eventing': { debut: [20, 29], peak: [30, 39], span: [15, 25], decline: 0.8 },
  'equestrian-jumping': { debut: [20, 30], peak: [32, 43], span: [17, 30], decline: 0.65 },
  golf: { debut: [18, 25], peak: [27, 35], span: [15, 26], decline: 0.9 },
  rowing: { debut: [18, 23], peak: [25, 31], span: [11, 19], decline: 1.2 },
  'canoe-sprint': { debut: [18, 23], peak: [24, 30], span: [10, 18], decline: 1.3 },
  'canoe-slalom': { debut: [17, 23], peak: [24, 30], span: [10, 18], decline: 1.3 },
  fencing: { debut: [17, 23], peak: [26, 33], span: [13, 22], decline: 1.0 },
  tennis: { debut: [16, 21], peak: [23, 28], span: [11, 19], decline: 1.4 },
  badminton: { debut: [17, 22], peak: [23, 28], span: [10, 17], decline: 1.5 },
  'table-tennis': { debut: [16, 22], peak: [23, 29], span: [11, 20], decline: 1.2 },
  'modern-pentathlon': { debut: [19, 24], peak: [26, 31], span: [10, 17], decline: 1.3 },
  triathlon: { debut: [19, 25], peak: [27, 33], span: [11, 18], decline: 1.2 },
  default: { debut: [18, 24], peak: [25, 31], span: [10, 18], decline: 1.3 },
  team: { debut: [18, 23], peak: [25, 30], span: [11, 18], decline: 1.25 },
}

export const countryTraditions = {
  USA: ['athletics','swimming','basketball','artistic-gymnastics','shooting'],
  CHN: ['diving','table-tennis','weightlifting','badminton','artistic-gymnastics','shooting'],
  GBR: ['athletics','cycling-track','rowing','sailing','swimming'],
  FRA: ['fencing','judo','cycling-road','handball','athletics'],
  GER: ['canoe-sprint','rowing','cycling-track','equestrian-eventing','athletics'],
  URS: ['artistic-gymnastics','wrestling','weightlifting','athletics','fencing'],
  RUS: ['artistic-gymnastics','wrestling','fencing','artistic-swimming','athletics'],
  JPN: ['judo','wrestling','artistic-gymnastics','swimming','skateboarding'],
  AUS: ['swimming','rowing','sailing','cycling-track','hockey'],
  HUN: ['fencing','canoe-sprint','swimming','water-polo','wrestling'],
  ITA: ['fencing','cycling-road','shooting','swimming','rowing'],
  NED: ['cycling-track','cycling-road','rowing','swimming','hockey'],
  KEN: ['athletics'], ETH: ['athletics'], JAM: ['athletics'],
  CUB: ['boxing','wrestling','judo','athletics'],
  KOR: ['archery','taekwondo','fencing','shooting'],
  IND: ['hockey','shooting','wrestling','badminton'],
  ESP: ['sailing','canoe-sprint','basketball','football','taekwondo'],
  BRA: ['football','volleyball','beach-volleyball','judo','sailing'],
  CAN: ['swimming','rowing','athletics','canoe-sprint'],
  NZL: ['rowing','sailing','canoe-sprint','rugby-sevens'],
  TUR: ['wrestling','weightlifting','taekwondo'],
  IRI: ['wrestling','weightlifting','taekwondo'],
  GEO: ['wrestling','judo','weightlifting'],
  BUL: ['wrestling','weightlifting','rhythmic-gymnastics'],
  ROU: ['rowing','artistic-gymnastics','canoe-sprint'],
  POL: ['athletics','canoe-sprint','weightlifting'],
  NOR: ['athletics','rowing','handball'],
  SWE: ['athletics','wrestling','swimming','equestrian-jumping'],
  DEN: ['cycling-track','rowing','sailing','handball'],
  GRE: ['weightlifting','athletics','sailing'],
  MEX: ['diving','taekwondo','archery'],
  COL: ['cycling-track','weightlifting','athletics'],
  ARG: ['hockey','football','sailing','basketball'],
  RSA: ['athletics','swimming','rowing'],
  EGY: ['weightlifting','wrestling','fencing'],
}

export const historicalEraFactors = [
  { from: 1896, to: 1912, science: 0.70, access: 0.35 },
  { from: 1920, to: 1948, science: 0.77, access: 0.48 },
  { from: 1952, to: 1976, science: 0.86, access: 0.66 },
  { from: 1980, to: 1996, science: 0.94, access: 0.84 },
  { from: 2000, to: 9999, science: 1.00, access: 1.00 },
]
