export const countryThemes = {
  GRE: { accent:'#1f62b3', accent2:'#d9a62e', background:'#f4f8fd', header:'#164d8f', text:'#15243a', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  FRA: { accent:'#d6293e', accent2:'#174a9c', background:'#ffffff', header:'#174a9c', text:'#17365f', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  ESP: { accent:'#b51424', accent2:'#d9a514', background:'#fff4b8', header:'#a50f1f', text:'#211b16', panel:'#fffdf3', font:'Georgia, Times New Roman, serif' },
  GBR: { accent:'#c7253e', accent2:'#203f83', background:'#f5f7fb', header:'#17356f', text:'#15223a', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  GER: { accent:'#bd2637', accent2:'#d7a91c', background:'#f5f3ed', header:'#202020', text:'#1b1b1b', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  ITA: { accent:'#1d8a58', accent2:'#c92d3e', background:'#f5faf7', header:'#12633f', text:'#173428', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  NED: { accent:'#ec6a24', accent2:'#24498a', background:'#fff8f1', header:'#24498a', text:'#182b4d', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  SWE: { accent:'#e2b62b', accent2:'#2867a8', background:'#eef6ff', header:'#1f5b98', text:'#12314f', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  DEN: { accent:'#c92338', accent2:'#ffffff', background:'#fff7f8', header:'#9f1c2c', text:'#312128', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  POL: { accent:'#cf2940', accent2:'#ffffff', background:'#fff8f9', header:'#a51c31', text:'#34222a', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  CZE: { accent:'#c42b3e', accent2:'#28539a', background:'#f5f8fd', header:'#21427a', text:'#1d2b45', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  HUN: { accent:'#24805b', accent2:'#c82e3e', background:'#f5faf7', header:'#1b6548', text:'#1b3429', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  TUR: { accent:'#c92538', accent2:'#ffffff', background:'#fff6f7', header:'#a7192b', text:'#32171c', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  EGY: { accent:'#bd2636', accent2:'#c99a2d', background:'#fbf3e4', header:'#241d18', text:'#2d241d', panel:'#fffdf8', font:'Georgia, Times New Roman, serif' },
  RSA: { accent:'#16865a', accent2:'#d4a528', background:'#f3faf6', header:'#174b3a', text:'#18372d', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  KEN: { accent:'#b32232', accent2:'#16804b', background:'#f6f4ed', header:'#151515', text:'#24211d', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  MAR: { accent:'#b51f32', accent2:'#14744c', background:'#fff8f3', header:'#8d1727', text:'#34221e', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  NGR: { accent:'#198757', accent2:'#ffffff', background:'#f2faf6', header:'#11623f', text:'#17372b', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  ETH: { accent:'#caa529', accent2:'#21804f', background:'#fff8de', header:'#9e2f32', text:'#30251d', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  JPN: { accent:'#c91d3a', accent2:'#4a4a4a', background:'#fffafa', header:'#8e1830', text:'#27232a', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  KOR: { accent:'#d53c48', accent2:'#26549a', background:'#f7f9fd', header:'#263f76', text:'#19243a', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  CHN: { accent:'#d62a32', accent2:'#d5aa27', background:'#fff5ec', header:'#9f1c25', text:'#321d1b', panel:'#fffdf8', font:'Georgia, Times New Roman, serif' },
  IND: { accent:'#e07b25', accent2:'#207644', background:'#fff9ef', header:'#24417b', text:'#21304a', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  THA: { accent:'#c82d45', accent2:'#263f83', background:'#fff7f8', header:'#243769', text:'#2e2230', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  SGP: { accent:'#d92e3f', accent2:'#ffffff', background:'#fff7f8', header:'#a31f30', text:'#312128', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  INA: { accent:'#cf2635', accent2:'#ffffff', background:'#fff8f8', header:'#9e1f2b', text:'#302326', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  QAT: { accent:'#8c1d48', accent2:'#d8b66c', background:'#fbf4f7', header:'#651235', text:'#2f1f27', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  UAE: { accent:'#c52a37', accent2:'#16804b', background:'#f8faf7', header:'#1e1e1e', text:'#242424', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  ARG: { accent:'#49a4d5', accent2:'#d5ab2d', background:'#f1f9fd', header:'#28769f', text:'#17364a', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  BRA: { accent:'#208454', accent2:'#d8ad27', background:'#f5fbef', header:'#17613d', text:'#1c3829', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  CHI: { accent:'#c62a3c', accent2:'#284d94', background:'#f7f8fc', header:'#243f78', text:'#1e2a43', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  PER: { accent:'#d12d3e', accent2:'#ffffff', background:'#fff8f8', header:'#a72231', text:'#332329', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  COL: { accent:'#d4a920', accent2:'#25498c', background:'#fff9dc', header:'#b11f36', text:'#30291c', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  MEX: { accent:'#167b4d', accent2:'#bd2636', background:'#f5faf7', header:'#175f42', text:'#1b3329', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  USA: { accent:'#c52d3f', accent2:'#24498a', background:'#f5f7fb', header:'#1e3e79', text:'#192941', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  CAN: { accent:'#d12a3c', accent2:'#ffffff', background:'#fff8f8', header:'#a71f30', text:'#312128', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  CUB: { accent:'#c72d3f', accent2:'#244a8a', background:'#f8f9fc', header:'#213f75', text:'#1c2940', panel:'#ffffff', font:'Georgia, Times New Roman, serif' },
  AUS: { accent:'#d5ad2a', accent2:'#1e6c52', background:'#f4faf6', header:'#173f4f', text:'#18323a', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
  NZL: { accent:'#252525', accent2:'#c53243', background:'#f5f6f7', header:'#181818', text:'#232323', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' },
}

export const hostCities = [
  { city:'Paris', countryCode:'FRA', continent:'Europe', preferredSports:['fencing','judo','cycling-road','handball'] },
  { city:'Madrid', countryCode:'ESP', continent:'Europe', preferredSports:['football','basketball','tennis','canoe-sprint'] },
  { city:'Barcelona', countryCode:'ESP', continent:'Europe', preferredSports:['football','sailing','basketball','cycling-track'] },
  { city:'London', countryCode:'GBR', continent:'Europe', preferredSports:['athletics','rowing','cycling-track','boxing'] },
  { city:'Manchester', countryCode:'GBR', continent:'Europe', preferredSports:['football','cycling-track','boxing','rugby-sevens'] },
  { city:'Berlin', countryCode:'GER', continent:'Europe', preferredSports:['athletics','canoe-sprint','rowing','cycling-track'] },
  { city:'Munich', countryCode:'GER', continent:'Europe', preferredSports:['canoe-slalom','rowing','cycling-road','equestrian-eventing'] },
  { city:'Rome', countryCode:'ITA', continent:'Europe', preferredSports:['fencing','cycling-road','rowing','water-polo'] },
  { city:'Milan', countryCode:'ITA', continent:'Europe', preferredSports:['cycling-track','fencing','football','basketball'] },
  { city:'Amsterdam', countryCode:'NED', continent:'Europe', preferredSports:['cycling-track','cycling-road','rowing','hockey'] },
  { city:'Stockholm', countryCode:'SWE', continent:'Europe', preferredSports:['athletics','equestrian-jumping','swimming','wrestling'] },
  { city:'Copenhagen', countryCode:'DEN', continent:'Europe', preferredSports:['cycling-track','rowing','sailing','handball'] },
  { city:'Warsaw', countryCode:'POL', continent:'Europe', preferredSports:['athletics','canoe-sprint','weightlifting','volleyball'] },
  { city:'Prague', countryCode:'CZE', continent:'Europe', preferredSports:['canoe-slalom','athletics','shooting','rowing'] },
  { city:'Budapest', countryCode:'HUN', continent:'Europe', preferredSports:['fencing','canoe-sprint','swimming','water-polo'] },
  { city:'Istanbul', countryCode:'TUR', continent:'Europe', preferredSports:['wrestling','weightlifting','taekwondo','basketball'] },

  { city:'Cairo', countryCode:'EGY', continent:'Africa', preferredSports:['weightlifting','wrestling','fencing','football'] },
  { city:'Cape Town', countryCode:'RSA', continent:'Africa', preferredSports:['athletics','swimming','rowing','rugby-sevens'] },
  { city:'Johannesburg', countryCode:'RSA', continent:'Africa', preferredSports:['athletics','boxing','rugby-sevens','swimming'] },
  { city:'Nairobi', countryCode:'KEN', continent:'Africa', preferredSports:['athletics','rugby-sevens','boxing','volleyball'] },
  { city:'Casablanca', countryCode:'MAR', continent:'Africa', preferredSports:['athletics','boxing','football','taekwondo'] },
  { city:'Lagos', countryCode:'NGR', continent:'Africa', preferredSports:['athletics','football','basketball','weightlifting'] },
  { city:'Addis Ababa', countryCode:'ETH', continent:'Africa', preferredSports:['athletics','cycling-road','boxing','taekwondo'] },

  { city:'Tokyo', countryCode:'JPN', continent:'Asia', preferredSports:['judo','wrestling','artistic-gymnastics','baseball'] },
  { city:'Osaka', countryCode:'JPN', continent:'Asia', preferredSports:['judo','baseball','swimming','skateboarding'] },
  { city:'Seoul', countryCode:'KOR', continent:'Asia', preferredSports:['archery','taekwondo','fencing','shooting'] },
  { city:'Beijing', countryCode:'CHN', continent:'Asia', preferredSports:['diving','table-tennis','badminton','weightlifting'] },
  { city:'Shanghai', countryCode:'CHN', continent:'Asia', preferredSports:['swimming','table-tennis','badminton','sport-climbing'] },
  { city:'Mumbai', countryCode:'IND', continent:'Asia', preferredSports:['cricket','hockey','badminton','wrestling'] },
  { city:'New Delhi', countryCode:'IND', continent:'Asia', preferredSports:['hockey','shooting','wrestling','badminton'] },
  { city:'Bangkok', countryCode:'THA', continent:'Asia', preferredSports:['weightlifting','boxing','taekwondo','badminton'] },
  { city:'Singapore', countryCode:'SGP', continent:'Asia', preferredSports:['swimming','table-tennis','sailing','badminton'] },
  { city:'Jakarta', countryCode:'INA', continent:'Asia', preferredSports:['badminton','weightlifting','archery','sport-climbing'] },
  { city:'Doha', countryCode:'QAT', continent:'Asia', preferredSports:['athletics','football','handball','shooting'] },
  { city:'Dubai', countryCode:'UAE', continent:'Asia', preferredSports:['judo','shooting','cycling-road','golf'] },

  { city:'Buenos Aires', countryCode:'ARG', continent:'South America', preferredSports:['hockey','football','basketball','sailing'] },
  { city:'Rio de Janeiro', countryCode:'BRA', continent:'South America', preferredSports:['football','volleyball','beach-volleyball','judo'] },
  { city:'São Paulo', countryCode:'BRA', continent:'South America', preferredSports:['football','basketball','judo','volleyball'] },
  { city:'Santiago', countryCode:'CHI', continent:'South America', preferredSports:['tennis','rowing','cycling-track','football'] },
  { city:'Lima', countryCode:'PER', continent:'South America', preferredSports:['shooting','surfing','weightlifting','volleyball'] },
  { city:'Bogotá', countryCode:'COL', continent:'South America', preferredSports:['cycling-track','cycling-road','weightlifting','athletics'] },

  { city:'Mexico City', countryCode:'MEX', continent:'North America', preferredSports:['diving','taekwondo','archery','football'] },
  { city:'New York', countryCode:'USA', continent:'North America', preferredSports:['athletics','basketball','boxing','swimming'] },
  { city:'Los Angeles', countryCode:'USA', continent:'North America', preferredSports:['athletics','swimming','basketball','baseball'] },
  { city:'Chicago', countryCode:'USA', continent:'North America', preferredSports:['basketball','athletics','boxing','wrestling'] },
  { city:'Toronto', countryCode:'CAN', continent:'North America', preferredSports:['swimming','rowing','basketball','canoe-sprint'] },
  { city:'Montreal', countryCode:'CAN', continent:'North America', preferredSports:['diving','swimming','cycling-track','artistic-gymnastics'] },
  { city:'Havana', countryCode:'CUB', continent:'North America', preferredSports:['boxing','wrestling','judo','athletics'] },

  { city:'Sydney', countryCode:'AUS', continent:'Oceania', preferredSports:['swimming','rowing','sailing','rugby-sevens'] },
  { city:'Melbourne', countryCode:'AUS', continent:'Oceania', preferredSports:['swimming','cycling-track','basketball','rowing'] },
  { city:'Brisbane', countryCode:'AUS', continent:'Oceania', preferredSports:['swimming','rugby-sevens','canoe-sprint','hockey'] },
  { city:'Auckland', countryCode:'NZL', continent:'Oceania', preferredSports:['rowing','sailing','canoe-sprint','rugby-sevens'] },
]

export const worldEventArchetypes = [
  { id:'national-plan', tone:'positive', title:'A national medal plan is approved', body:'A multi-year public programme channels resources into elite coaching and talent identification.', overall:5, youth:7, facilities:3, sport:8 },
  { id:'academy', tone:'positive', title:'A new high-performance academy opens', body:'Centralized facilities and international coaches strengthen the country’s Olympic pathway.', overall:2, youth:6, facilities:10, sport:6 },
  { id:'private-funding', tone:'positive', title:'Private funding transforms an Olympic programme', body:'A major commercial partnership finances equipment, travel and specialist coaches.', overall:5, youth:3, facilities:7, sport:10 },
  { id:'golden-generation', tone:'positive', title:'A golden generation begins to emerge', body:'Youth results suggest that a cluster of elite prospects could peak at the next Games.', overall:2, youth:10, facilities:2, sport:12 },
  { id:'coaching-revolution', tone:'positive', title:'Foreign coaches trigger a technical revolution', body:'New methods rapidly improve one national programme and its qualification prospects.', overall:2, youth:4, facilities:2, sport:14 },
  { id:'women-expansion', tone:'positive', title:'Women’s sport receives a historic expansion', body:'Scholarships and domestic leagues dramatically increase the depth of the women’s pathway.', overall:4, youth:9, facilities:3, sport:8 },
  { id:'diaspora-return', tone:'positive', title:'Elite diaspora athletes return to the national system', body:'International experience strengthens both the current team and the next coaching generation.', overall:3, youth:5, facilities:2, sport:9 },
  { id:'school-reform', tone:'positive', title:'School sport reform widens the talent base', body:'A new national curriculum brings structured competition to thousands of young athletes.', overall:3, youth:11, facilities:1, sport:5 },
  { id:'economic-boom', tone:'positive', title:'Economic growth unlocks a larger sports budget', body:'The Olympic committee expands training camps, science support and international competition.', overall:8, youth:4, facilities:6, sport:7 },
  { id:'technology', tone:'positive', title:'A sports-science breakthrough changes preparation', body:'Biomechanics and recovery systems deliver a measurable advantage in one discipline.', overall:2, youth:2, facilities:6, sport:13 },
  { id:'star-effect', tone:'positive', title:'A national star inspires a participation boom', body:'Clubs report record enrolment after a charismatic champion captures public attention.', overall:2, youth:9, facilities:2, sport:11 },
  { id:'regional-games', tone:'positive', title:'A successful regional Games leaves a strong legacy', body:'Venues, volunteers and coaching networks are redirected toward Olympic preparation.', overall:4, youth:4, facilities:8, sport:7 },
  { id:'economic-crisis', tone:'negative', title:'An economic crisis forces deep sports cuts', body:'Travel, camps and development grants are reduced during a difficult Olympic cycle.', overall:-8, youth:-5, facilities:-4, sport:-9 },
  { id:'federation-scandal', tone:'negative', title:'A federation scandal destabilizes preparation', body:'Leadership turmoil and suspended funding damage one of the country’s priority sports.', overall:-2, youth:-3, facilities:-1, sport:-15 },
  { id:'war-disruption', tone:'negative', title:'Conflict disrupts the national Olympic pathway', body:'Training centres close and athletes struggle to access international qualification events.', overall:-10, youth:-8, facilities:-9, sport:-10, delegation:0.72 },
  { id:'boycott-threat', tone:'negative', title:'A boycott threat hangs over qualification', body:'Federations prepare uncertain rosters while diplomatic negotiations continue.', overall:-3, youth:-1, facilities:0, sport:-5, delegation:0.84 },
  { id:'natural-disaster', tone:'negative', title:'A natural disaster damages key training venues', body:'Reconstruction diverts resources and several teams relocate abroad.', overall:-4, youth:-3, facilities:-10, sport:-7 },
  { id:'doping-crisis', tone:'negative', title:'A doping crisis forces a complete rebuild', body:'Suspensions and stricter controls weaken the current cycle but may improve long-term credibility.', overall:-5, youth:1, facilities:-2, sport:-14 },
  { id:'coach-exodus', tone:'negative', title:'A coaching exodus weakens a traditional power', body:'Several leading specialists accept contracts abroad, leaving gaps in the elite pathway.', overall:-3, youth:-4, facilities:0, sport:-12 },
  { id:'federation-collapse', tone:'negative', title:'A national federation loses recognition', body:'Administrative failure blocks access to camps and qualification competitions.', overall:-5, youth:-5, facilities:-3, sport:-16, delegation:0.9 },
  { id:'reconciliation', tone:'mixed', title:'Sport becomes part of a national reconciliation effort', body:'A fragile political opening produces new teams, shared facilities and international invitations.', overall:4, youth:6, facilities:3, sport:5 },
  { id:'refugee-pathway', tone:'mixed', title:'A refugee athlete pathway is created', body:'Displaced competitors receive access to training, travel documents and qualification opportunities.', overall:1, youth:3, facilities:1, sport:4 },
  { id:'rule-change', tone:'mixed', title:'A federation rule change reshapes qualification', body:'The new pathway rewards depth and consistency rather than a single championship result.', overall:0, youth:2, facilities:0, sport:5 },
  { id:'climate-shift', tone:'mixed', title:'Climate conditions force a preparation rethink', body:'Teams alter camps, schedules and venue choices to adapt to increasingly difficult conditions.', overall:-1, youth:0, facilities:2, sport:-2 },
]

const worldEventContexts = [
  { id:'national', label:'National response', lead:'A nationwide decision accelerates the effect:', multiplier:1 },
  { id:'federation', label:'Federation turning point', lead:'The governing federation becomes the centre of the story:', multiplier:0.9 },
  { id:'regional', label:'Regional programme', lead:'A powerful regional hub changes the national outlook:', multiplier:0.82 },
  { id:'elite', label:'Elite-system shock', lead:'The high-performance system feels the impact first:', multiplier:1.08 },
  { id:'youth', label:'Youth-pathway effect', lead:'The consequences spread through schools, clubs and junior teams:', multiplier:0.94 },
  { id:'international', label:'International intervention', lead:'Foreign partners and international federations amplify the development:', multiplier:1.02 },
]

export const worldEventPool = worldEventArchetypes.flatMap((archetype) => worldEventContexts.map((context) => ({
  ...archetype,
  id: `${archetype.id}-${context.id}`,
  archetypeId: archetype.id,
  title: `${archetype.title} · ${context.label}`,
  body: `${context.lead} ${archetype.body}`,
  overall: Math.round(archetype.overall * context.multiplier),
  youth: Math.round(archetype.youth * (context.id === 'youth' ? 1.25 : context.multiplier)),
  facilities: Math.round(archetype.facilities * (context.id === 'regional' ? 1.18 : context.multiplier)),
  sport: Math.round(archetype.sport * (context.id === 'elite' ? 1.18 : context.multiplier)),
})))

export const WORLD_EVENT_POOL_SIZE = worldEventPool.length

export function themeForCountry(code) {
  return countryThemes[code] || { accent:'#168b97', accent2:'#d4a229', background:'#eef3f7', header:'#0c2d42', text:'#172033', panel:'#ffffff', font:'Inter, ui-sans-serif, system-ui, sans-serif' }
}
